### ISSUE TITLE
Proposal: weekly sync on Tuesdays only

### ISSUE THREAD

**Issue by artursouza** [dapr/community#146]
Today, we have weekly sync on Tuesdays and Thursdays at 9am and 9pm PST. Instead, I propose we keep it on Tuesdays 9am and 9pm PST only and remove Thursdays. This way, we optimize towards asynchronous communication (GH issues, PRs, Discord, etc) instead of calls. I believe this will lead to less meeting fatigue for members that are active in the release and also be inclusive towards the community with better async communication.

Reference: https://github.com/dapr/community#milestone-sync-meetings

**Comment by yaron2** [comment]
I agree.

**Comment by berndverst** [comment]
I also agree (as Python SDK maintainer)

**Comment by msfussell** [comment]
I support this, but feel that;
1)  There is an event/calendar series so that people know where to join and that the meeting is happening. I for one was not always sure that the 9PM meeting occurred
2) The list of people in the release channel is updated and anyone who is a Dapr member can join this Discord channel
3) The we over communicate the milestone stages (planning, coding, pre-flight, endgame) in the Discord General channel for the community point to the release planning issue
4)  Maintainers come prepared to the Tues meeting having done updates and triage of issues and that the release person sets this expectation in advance
