### ISSUE TITLE
May 3rd 2022, Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#159]
Dapr Community Meetings

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on May 3rd, 2022, at 10:00am PST. The meeting agenda will be finalized by a Community Call Host days prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by msfussell** [comment]
Agenda ideas
1) https://github.com/dapr/community/issues/158#issuecomment-1090788687

**Comment by adamreed90** [comment]
I would like to see a talk on the **current** best practices for ASP.NET Core based applications. For example, the documentation shows using Invoke functions via the SDK to call these services which has since been deprecated. Specifically interesting to me, calling ASP.NET Core gRPC API's via Dapr. Also, any talk on Blazor WASM and ASP.NET Core APIs are also points of interest for me personally! :D
