### ISSUE TITLE
May 17th 2022 Community Meeting Agenda

### ISSUE THREAD

**Issue by msfussell** [dapr/community#164]
**Dapr Community Meetings**

Every two weeks we host a community meeting to showcase new features, review upcoming milestones, and engage in Q&A with the Dapr community - all are welcome, and we encourage participation.

The purpose of this thread is to form a discussion amongst the Dapr community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on May 17th at 7:30pm Pacific Time  PST. The meeting agenda is finalized by a Community Call Host prior to the meeting.

Thank you and we look forward to hearing your input.

**Comment by cveld** [comment]
Dapr seems very interesting to simplify microservice development! I am preparing for a talk on 12 May 2022 on Dapr on the Dutch conference TEQnation. During this process I collected some questions:
- Tye Blazor Hotreload support -- I believe Tye is running with "dotnet watch run" which disables hotreload.
- Service discovery across azure resources. E.g. from AKS through API Management to backend services (app service, on-premise, etc.). I see references to HashiCorp Consul. I would love to see a demo. Is this the easiest or best solution? Maybe other solutions are considered as well, more native to Azure.
- Local development without credentials -- i.e. in AKS you will be leveraging MSI. Locally you would like to leverage some locally stored credential I believe your guidance is to just set up a json file based secrets store, but this requires a separate service principal.
- Relational and graph database support. Why is odata support for single tables being added, but more complex relational or graph queries left out. Would be helpful to see some written considerations on this topic
- Wasm binaries for components - I suspect the goal is to sideload these binaries in the same process scope of the app so that grpc is not required
- dotnet HttpClient for Dapr invocations. I found some github issue with some guidance, maybe good to discuss

Just to note, I have not seen any application of dapr for production workloads yet in my network. Are there any large Dutch organizations adopting it?

**Comment by msfussell** [comment]
@cveld - The link is always posted to Twitter and you can find this on the Readme for this repo. See https://github.com/dapr/community#community-meetings Given your timezone, best to join the call on the 31st May, which is your evening (ther 17th is now cancelled due to KubeCon). Looking forward to having you join and hearing your feedback.
