### ISSUE TITLE
Maintainer's etiquette 

### ISSUE THREAD

**Issue by artursouza** [dapr/community#289]
Dapr has a clear [code of conduct](https://github.com/dapr/community/blob/master/CODE-OF-CONDUCT.md). On the other hand, there can be behaviors that are not constructive to the community but still does not violate the code of conduct.

Possible examples:
- Not giving feedback on PRs within x days
- Closing a PR or issue "too quickly" before contributors have a chance to engage
- Discord messages or comments on PRs that can read as aggressive

We don't have training for maintainers yet but I think we should create an etiquette guideline to serve as a reference for our behavior. As we onboard more maintainers, the community should have a consistent experience with maintainers without "too much" variation.

This proposal does not dismiss the individual "touch" of each maintainer but the etiquette guideline can help cut some rough edges.

**Comment by berndverst** [comment]
- Closing a PR or issue too quickly: in general I agree. But there isn't a minimum period of time an issue must be open. For example if there is a request opened for something which maintainers previously decided is not in scope, it is perfectly acceptable to close the issue with explanation right away, rather than letting it linger. Another example is a request for something which is a duplicate or covers functionality that is already available. Or an issue opened that clearly is user error where the maintainer in a single response can provide all the necessary details to resolve the issue.
I do not see a problem with closing issues. That being said **as an alternative we can create a new label "resolved" and have Dapr Bot close the issue 7 days after the "resolved" label was applied.**

- Not giving feedback on PRs: This is difficult to measure. Maybe **we need a review bot that actually assigns approvers for review, and maintainers to review approved PRs**.

- "Discord messages or comments on PR that read as aggressive" -- **for this point we should simply refer to the code of conduct**. It does not make sense to set a separate standard for this. Also, we must consider cultural differences between maintainers. Another reason why referring to the code of conduct is better here.


FYI @paulyuk @johnewart @ItalyPaleAle
