### ISSUE TITLE
[Request]: Create a `setup-dapr` repo for a GitHub action

### ISSUE THREAD

**Issue by AaronCrawfis** [dapr/community#50]
Create a new repo to contain the code for a GitHub action which will setup the Dapr CLI on the build agent.

**Comment by DarqueWarrior** [comment]
Just for some more context and background. The name of the repo is following a pattern that @AaronCrawfis and I confirmed looking in the GitHub Actions Marketplace for similar tool installers. 

The Action is already functioning and I am using it in this pipeline [here ](https://github.com/DarqueWarrior/samples/blob/a30a52a45eaa95f98b029a3f53127965018cb682/.github/workflows/twitter.yml#L90).

Once this repo is created I will move the code with clean history to this repo.  The usage of this action will be as follows:

```
 - name: Install Dapr
    uses: dapr/setup-dapr@v1
    with:
       version: 1.0.0
```

This code was based on the setup-helm tool installer from Azure. It works on all platforms and should require no changes as long as the pattern for the download URL does not change.

Currently, it defaults to version 1.1.0 but as you can see from the example above you can set the value to any version you like.

After Microsoft Build one enhancement will be to have it use the GitHub API and determine the latest version and use that instead of the currently hardcoded default of 1.1.0. 

I can also see a potential pre-release boolean that would have the default release include the latest pre-release as well. 

If you want to review the code before it is moved it is [here](https://github.com/DarqueWarrior/setup-dapr).

**Comment by artursouza** [comment]
Can the repo have a more generic name to host more actions in the future?

Can we have multiple GitHub actions in the same repo?

**Comment by AaronCrawfis** [comment]
> Can the repo have a more generic name to host more actions in the future?
> 
> Can we have multiple GitHub actions in the same repo?

Each action requires its own repo in order to publish to the GitHub marketplace: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

**Comment by yaron2** [comment]
Unfortunate it's a repo per action. I think we can try and see how a repo in the `dapr` org goes, and if needed we might mandate creating a separate org like `dapr-github` that contains the actions repos.

/cc @msfussell

**Comment by DarqueWarrior** [comment]
How many more actions are people thinking we might need?  Once Dapr is installed I expect people to just run the desired commands.

**Comment by artursouza** [comment]
@DarqueWarrior Just making sure we don't get into a future problem of "too many small repos". I am fine with this new repo.

**Comment by DarqueWarrior** [comment]
I have a few cycles this week. @AaronCrawfis or @artursouza can one of you create the repo so I can move the code?

**Comment by AaronCrawfis** [comment]
> I have a few cycles this week. @AaronCrawfis or @artursouza can one of you create the repo so I can move the code?

I don't have access. @artursouza or @yaron2 will need to initialize the repo

**Comment by DarqueWarrior** [comment]
@artursouza said the only person that has permission to create the repo is @yaron2. Is this something we can do this week? Next week is build where I have a demo of this being used. If It is created this week it will be June before I can move this.

**Comment by AaronCrawfis** [comment]
https://github.com/dapr/setup-dapr
