### ISSUE TITLE
Proposal: deprecate PHP SDK

### ISSUE THREAD

**Issue by artursouza** [dapr/community#544]
I would like to propose for the PHP SDK to be archived.

**Comment by JoshVanL** [comment]
+1 binding

**Comment by Mat-Moo** [comment]
I'd like to know why? There is no context behind this proposal and we are exploring Dapr it in order to give us better connectivity php->azure - MS have already killed the azure php sdk, and making it harder and harder for us to use Azure. This enables us to continue our builds and @withinboredom is already applying updates to it

**Comment by yaron2** [comment]
@Mat-Moo the SDK hasn't had a commit in over a year. @withinboredom will you be able to come back as a maintainer? (that would be amazing).

**Comment by withinboredom** [comment]
I've been back :) but during my absence I've lost any way to communicate to people other than github -- I've sent emails but they have bounced. As mentioned in https://github.com/dapr/php-sdk/issues/144#issuecomment-2326590463, I'm working on a complete refactoring for the workflow features.

I'm also not sure where this proposal comes from... seems kinda random.

**Comment by yaron2** [comment]
Closing as the SDK now has a maintainer in place
