### ISSUE TITLE
The name of this project is confusing

### ISSUE THREAD

**Issue by funkybunchesofoats-ih** [dapr/community#561]
Why did you make a DAPR project, when DAPPER has been around for years? More than a decade.
Now we when we talk about coding and someone mentions DAPR, we have to ask which friggin one.
Come on.

**Comment by yaron2** [comment]
This has been discussed in length before when the project was just starting out. The short answer is, at the time of launching the project creators were not aware of the Dapper project at all, and as Dapr gained much momentum very quickly, a name change was deemed unnecessary, after consuling with the Dapper's project creators. Since there is no action item for this issue, I'm closing this.
